name: DisplayEntityBuilderTool
version: '${project.version}'
main: dev.twme.displayentitybuildertool.DisplayEntityBuilderTool
api-version: '1.20'
authors: [TWME]
website: https://github.com/TWME-TW/DisplayEntityBuilderTool

commands:
  standslab:
    aliases:
      - standslab
    permission: displayentitybuildtool.gui.slab
  standstairs:
    aliases:
      - standstairs
    permission: displayentitybuildtool.gui.stairs

permissions:
  displayentitybuildtool.gui.slab:
    default: op
  displayentitybuildtool.gui.stairs:
    default: op
  displayentitybuildtool.place:
    default: op
  displayentitybuildtool.break:
    default: op
