name: DisplayEntityBuilderTool
version: '${project.version}'
main: land.builders.displayentitybuildertool.DisplayEntityBuilderTool
api-version: '1.20'
authors: [TWME]
softdepend:
  - GriefDefender
commands:
  standslab:
    aliases:
      - standslab
    permission: displayentitybuildtool.gui.slab
  standstairs:
    aliases:
      - aliases
    permission: displayentitybuildtool.gui.stairs

permissions:
  displayentitybuildtool.gui.slab:
    default: op
  displayentitybuildtool.gui.stairs:
    default: op
  displayentitybuildtool.place:
    default: op
  displayentitybuildtool.break:
    default: op
